{% set name = "recurring-ical-events" %}
{% set version = "3.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/recurring_ical_events-{{ version }}.tar.gz
  sha256: 8eb7be7a3ebd322b942fde74dbfb3c230010ab49e1d9eea1e9ea2201c1e4da93

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - icalendar >=6.1.0,<7.0.0
    - python-dateutil >=2.8.1,<3.0.0
    - x-wr-timezone >=1.0.0,<3.0.0
    - python-tzdata


test:
  imports:
    - recurring_ical_events
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/niccokunzmann/python-recurring-ical-events
  summary: A Python module which repeats ICalendar events by RRULE, RDATE and EXDATE.
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdido
