{% set name = "recurring-ical-events" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/recurring_ical_events-{{ version }}.tar.gz
  sha256: ef8d2d278c5aa0f28102c20921edbe1926c9a6d91bf8297c633adef0111866d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - icalendar >=5.0.9
    - pytz >=2023.3
    - python-dateutil >=2.8.1
    - x-wr-timezone <1.0.0
    - tzdata >=2024a

test:
  imports:
    - recurring_ical_events
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/niccokunzmann/python-recurring-ical-events
  summary: A Python module which repeats ICalendar events by RRULE, RDATE and EXDATE.
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdido
